### ISSUE TITLE
Fatal error on setup keys?

### ISSUE THREAD

**Issue by ghost** [DHS/wp-gocardless#13]
I get this error even before entering gocardless details

Fatal error: Uncaught exception 'GoCardless_ApiException' with message 'Unknown error' in C:\xampp\htdocs\builders\scc\wp-content\plugins\gocardless-wordpress-plugin\lib\GoCardless\Request.php:177 Stack trace: #0 C:\xampp\htdocs\builders\scc\wp-content\plugins\gocardless-wordpress-plugin\lib\GoCardless\Request.php(24): GoCardless_Request::call('get', 'https://gocardl...', Array) #1 [internal function]: GoCardless_Request::get('https://gocardl...', Array) #2 C:\xampp\htdocs\builders\scc\wp-content\plugins\gocardless-wordpress-plugin\lib\GoCardless\Client.php(452): call_user_func('GoCardless_Requ...', 'https://gocardl...', Array) #3 C:\xampp\htdocs\builders\scc\wp-content\plugins\gocardless-wordpress-plugin\lib\GoCardless\Merchant.php(54): GoCardless_Client->request('get', '/merchants/') #4 C:\xampp\htdocs\builders\scc\wp-content\plugins\gocardless-wordpress-plugin\admin.php(50): GoCardless_Merchant::find('') #5 C:\xampp\htdocs\builders\scc\wp-content\plugins\gocardless-wordpress-plugin\admin.php(30): gocardless_admin_dashb in C:\xampp\htdocs\builders\scc\wp-content\plugins\gocardless-wordpress-plugin\lib\GoCardless\Request.php on line 177

**Comment by MamoonaShuja** [comment]
Same issue is there any solution u find??
